In [ ]:
#!pip install scikeras==0.13.0 scikit-learn==1.5.2

Requirement already satisfied: scikeras==0.13.0 in /usr/local/lib/python3.12/dist-packages (0.13.0)
Requirement already satisfied: scikit-learn==1.5.2 in /usr/local/lib/python3.12/dist-packages (1.5.2)
Requirement already satisfied: keras>=3.2.0 in /usr/local/lib/python3.12/dist-packages (from scikeras==0.13.0) (3.13.2)
Requirement already satisfied: numpy>=1.19.5 in /usr/local/lib/python3.12/dist-packages (from scikit-learn==1.5.2) (2.0.2)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn==1.5.2) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn==1.5.2) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn==1.5.2) (3.6.0)
Requirement already satisfied: absl-py in /usr/local/lib/python3.12/dist-packages (from keras>=3.2.0->scikeras==0.13.0) (1.4.0)
Requirement already satisfied: rich in /usr/local/lib/python3.12/dist-packages (from keras>=3.2.0->scikeras==0.13.0) (13.9.4)
Requirement already satisfied: namex in /usr/local/lib/python3.12/dist-packages (from keras>=3.2.0->scikeras==0.13.0) (0.1.0)
Requirement already satisfied: h5py in /usr/local/lib/python3.12/dist-packages (from keras>=3.2.0->scikeras==0.13.0) (3.16.0)
Requirement already satisfied: optree in /usr/local/lib/python3.12/dist-packages (from keras>=3.2.0->scikeras==0.13.0) (0.19.1)
Requirement already satisfied: ml-dtypes in /usr/local/lib/python3.12/dist-packages (from keras>=3.2.0->scikeras==0.13.0) (0.5.4)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from keras>=3.2.0->scikeras==0.13.0) (26.2)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from optree->keras>=3.2.0->scikeras==0.13.0) (4.16.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras>=3.2.0->scikeras==0.13.0) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras>=3.2.0->scikeras==0.13.0) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich->keras>=3.2.0->scikeras==0.13.0) (0.1.2)

In [5]:
import pandas as pd
import numpy as np
import tensorflow as tf
from sklearn.model_selection import GridSearchCV
import kagglehub
from tensorflow.keras.models import Sequential
from scikeras.wrappers import KerasClassifier

In [6]:
df =pd.read_csv('/content/sample_data/diabetes.csv')
# carrega o dataset

In [7]:
df.head()
# verifica primeiras linhas

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [8]:
df.isnull().sum()
# verifica se há necessidade de limpeza

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [9]:
x = df[['Pregnancies','Glucose','BloodPressure','SkinThickness','Insulin','BMI','DiabetesPedigreeFunction','Age']]
y = df['Outcome']
# separa as features previsoras e a target

In [10]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
x_scaled = scaler.fit_transform(x)

In [11]:
y

0      1
1      0
2      1
3      0
4      1
      ..
763    0
764    0
765    0
766    1
767    0
Name: Outcome, Length: 768, dtype: int64

In [12]:
def rede (optimizer, loss, initializer, activation, neurons):
    # recebe os parametros do modelos para cada vez que mudar os parametros no grid search
    rede = Sequential([
        tf.keras.layers.InputLayer(shape=(8,)),
        # 8 features 8 neuronios de entrada
        tf.keras.layers.Dense(units=neurons, activation=activation, kernel_initializer=initializer),
        # camada oculta
        tf.keras.layers.Dropout(rate=0.2),
        # ajuda a minimizar o overfitting
        tf.keras.layers.Dense(units=neurons, activation=activation, kernel_initializer=initializer),
        # camada oculta
        tf.keras.layers.Dropout(rate=0.2),
        tf.keras.layers.Dense(units=1,activation='sigmoid')
        # um neuronio de saida
    ])
    rede.compile(optimizer=optimizer,loss=loss, metrics = ['binary_accuracy'])
    return rede

In [13]:
rede = KerasClassifier(model= rede)

In [14]:
params = {
    'batch_size':[10],
    'epochs':[50],
    'model__optimizer': ['adam','sgd'],
    'model__loss': ['binary_crossentropy'],
    'model__initializer': ['normal','uniform'],
    'model__activation': ['relu'],
    'model__neurons': [4,6]
}
# em um dict define todos os parametros que serao testados

In [15]:
gs = GridSearchCV(estimator=rede,param_grid=params, scoring='accuracy', cv=4)
# cria o modelo do grid search, com os parametros definidos no dict, cv significa o cross validation

In [16]:
gs = gs.fit(x_scaled,y)
# treina o modelo com diferentes parametros

Epoch 1/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - binary_accuracy: 0.6458 - loss: 0.6846
Epoch 2/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.6510 - loss: 0.6601
Epoch 3/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.6510 - loss: 0.6255
Epoch 4/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.6510 - loss: 0.5907
Epoch 5/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.6493 - loss: 0.5701
Epoch 6/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.6771 - loss: 0.5550
Epoch 7/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.7413 - loss: 0.5289
Epoch 8/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.7274 - loss: 0.5188
Epoch 9/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.7448 - loss: 0.5152
Epoch 10/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.7274 - loss: 0.5156
Epoch 11/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.7222 - loss: 0.5225
Epoch 12/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.7344 - loss: 0.5064
Epoch 13/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - binary_accuracy: 0.7344 - loss: 0.5170
Epoch 14/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.7309 - loss: 0.5173
Epoch 15/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.7378 - loss: 0.4998
Epoch 16/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.7448 - loss: 0.4974
Epoch 17/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.7378 - loss: 0.5016
Epoch 18/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.7396 - loss: 0.5016
Epoch 19/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - binary_accuracy: 0.7587 - loss: 0.4807
Epoch 20/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.7413 - loss: 0.4860
Epoch 21/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.7101 - loss: 0.4956
Epoch 22/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - binary_accuracy: 0.7222 - loss: 0.5044
Epoch 23/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - binary_accuracy: 0.7205 - loss: 0.5031
Epoch 24/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - binary_accuracy: 0.7413 - loss: 0.4761
Epoch 25/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - binary_accuracy: 0.7396 - loss: 0.4944
Epoch 26/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - binary_accuracy: 0.7535 - loss: 0.4935
Epoch 27/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - binary_accuracy: 0.7465 - loss: 0.4903
Epoch 28/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - binary_accuracy: 0.7726 - loss: 0.4783
Epoch 29/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - binary_accuracy: 0.7552 - loss: 0.4970
Epoch 30/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - binary_accuracy: 0.7569 - loss: 0.4954
Epoch 31/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - binary_accuracy: 0.7500 - loss: 0.4994
Epoch 32/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - binary_accuracy: 0.7639 - loss: 0.5112
Epoch 33/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - binary_accuracy: 0.7604 - loss: 0.4986
Epoch 34/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - binary_accuracy: 0.7465 - loss: 0.4954
Epoch 35/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - binary_accuracy: 0.7691 - loss: 0.4915
Epoch 36/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - binary_accuracy: 0.7708 - loss: 0.4930
Epoch 37/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - binary_accuracy: 0.7604 - loss: 0.4745
Epoch 38/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - binary_accuracy: 0.7517 - loss: 0.4909
Epoch 39/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - binary_accuracy: 0.7587 - loss: 0.5007
Epoch 40/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - binary_accuracy: 0.7622 - loss: 0.4898
Epoch 41/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - binary_accuracy: 0.7309 - loss: 0.5137
Epoch 42/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - binary_accuracy: 0.7517 - loss: 0.4831
Epoch 43/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - binary_accuracy: 0.7483 - loss: 0.4959
Epoch 44/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - binary_accuracy: 0.7656 - loss: 0.4885
Epoch 45/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - binary_accuracy: 0.7465 - loss: 0.4923
Epoch 46/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - binary_accuracy: 0.7604 - loss: 0.4891
Epoch 47/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - binary_accuracy: 0.7656 - loss: 0.4879
Epoch 48/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - binary_accuracy: 0.7656 - loss: 0.4854
Epoch 49/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - binary_accuracy: 0.7622 - loss: 0.4894
Epoch 50/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - binary_accuracy: 0.7656 - loss: 0.4885
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
Epoch 1/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - binary_accuracy: 0.6788 - loss: 0.6853
Epoch 2/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.7066 - loss: 0.6609
Epoch 3/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.7292 - loss: 0.6233
Epoch 4/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - binary_accuracy: 0.7465 - loss: 0.5786
Epoch 5/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.7413 - loss: 0.5483
Epoch 6/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - binary_accuracy: 0.7569 - loss: 0.5264
Epoch 7/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - binary_accuracy: 0.7830 - loss: 0.4993
Epoch 8/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.7830 - loss: 0.4989
Epoch 9/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.7812 - loss: 0.4852
Epoch 10/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.7674 - loss: 0.4819
Epoch 11/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.7812 - loss: 0.4909
Epoch 12/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - binary_accuracy: 0.7656 - loss: 0.4789
Epoch 13/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - binary_accuracy: 0.7847 - loss: 0.4793
Epoch 14/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - binary_accuracy: 0.7899 - loss: 0.4685
Epoch 15/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - binary_accuracy: 0.7847 - loss: 0.4636
Epoch 16/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - binary_accuracy: 0.7812 - loss: 0.4798
Epoch 17/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - binary_accuracy: 0.7708 - loss: 0.4860
Epoch 18/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - binary_accuracy: 0.7795 - loss: 0.4827
Epoch 19/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - binary_accuracy: 0.7778 - loss: 0.4662
Epoch 20/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - binary_accuracy: 0.7691 - loss: 0.4818
Epoch 21/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - binary_accuracy: 0.7708 - loss: 0.4778
Epoch 22/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - binary_accuracy: 0.7760 - loss: 0.4668
Epoch 23/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - binary_accuracy: 0.7812 - loss: 0.4812
Epoch 24/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - binary_accuracy: 0.7778 - loss: 0.4822
Epoch 25/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - binary_accuracy: 0.7691 - loss: 0.4810
Epoch 26/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - binary_accuracy: 0.7604 - loss: 0.4969
Epoch 27/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.7812 - loss: 0.4672
Epoch 28/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - binary_accuracy: 0.7760 - loss: 0.4707
Epoch 29/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - binary_accuracy: 0.7760 - loss: 0.4771
Epoch 30/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.7917 - loss: 0.4703
Epoch 31/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.7951 - loss: 0.4654
Epoch 32/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.7847 - loss: 0.4763
Epoch 33/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.7830 - loss: 0.4714
Epoch 34/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.7639 - loss: 0.4879
Epoch 35/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.7778 - loss: 0.4688
Epoch 36/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.7830 - loss: 0.4773
Epoch 37/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.7865 - loss: 0.4722
Epoch 38/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.7778 - loss: 0.4553
Epoch 39/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.7812 - loss: 0.4680
Epoch 40/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.7812 - loss: 0.4755
Epoch 41/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.7795 - loss: 0.4875
Epoch 42/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.8003 - loss: 0.4654
Epoch 43/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.7899 - loss: 0.4692
Epoch 44/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.7847 - loss: 0.4777
Epoch 45/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.7830 - loss: 0.4724
Epoch 46/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.7882 - loss: 0.4726
Epoch 47/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - binary_accuracy: 0.7847 - loss: 0.4621
Epoch 48/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.7674 - loss: 0.4837
Epoch 49/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.7743 - loss: 0.4801
Epoch 50/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - binary_accuracy: 0.7656 - loss: 0.4802
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
Epoch 1/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - binary_accuracy: 0.6493 - loss: 0.6813
Epoch 2/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.6510 - loss: 0.6478
Epoch 3/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.6597 - loss: 0.6054
Epoch 4/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - binary_accuracy: 0.6788 - loss: 0.5692
Epoch 5/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.7118 - loss: 0.5365
Epoch 6/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.7135 - loss: 0.5306
Epoch 7/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.7135 - loss: 0.5232
Epoch 8/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.7135 - loss: 0.5258
Epoch 9/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - binary_accuracy: 0.7222 - loss: 0.5242
Epoch 10/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.7274 - loss: 0.5086
Epoch 11/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.7483 - loss: 0.5091
Epoch 12/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.7135 - loss: 0.5063
Epoch 13/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.7378 - loss: 0.5081
Epoch 14/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.7378 - loss: 0.5003
Epoch 15/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - binary_accuracy: 0.7396 - loss: 0.4936
Epoch 16/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.7552 - loss: 0.4821
Epoch 17/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - binary_accuracy: 0.7274 - loss: 0.4994
Epoch 18/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - binary_accuracy: 0.7344 - loss: 0.4964
Epoch 19/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - binary_accuracy: 0.7361 - loss: 0.5032
Epoch 20/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - binary_accuracy: 0.7517 - loss: 0.5028
Epoch 21/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - binary_accuracy: 0.7448 - loss: 0.4971
Epoch 22/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - binary_accuracy: 0.7188 - loss: 0.5010
Epoch 23/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - binary_accuracy: 0.7413 - loss: 0.4981
Epoch 24/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - binary_accuracy: 0.7344 - loss: 0.5027
Epoch 25/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - binary_accuracy: 0.7413 - loss: 0.4972
Epoch 26/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - binary_accuracy: 0.7500 - loss: 0.4873
Epoch 27/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - binary_accuracy: 0.7361 - loss: 0.4840
Epoch 28/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - binary_accuracy: 0.7500 - loss: 0.5087
Epoch 29/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - binary_accuracy: 0.7535 - loss: 0.4850
Epoch 30/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.7587 - loss: 0.4903
Epoch 31/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.7517 - loss: 0.5093
Epoch 32/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.7691 - loss: 0.4883
Epoch 33/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - binary_accuracy: 0.7604 - loss: 0.5060
Epoch 34/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - binary_accuracy: 0.7708 - loss: 0.4861
Epoch 35/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.7569 - loss: 0.5007
Epoch 36/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.7483 - loss: 0.4906
Epoch 37/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.7604 - loss: 0.4990
Epoch 38/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - binary_accuracy: 0.7465 - loss: 0.5078
Epoch 39/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.7552 - loss: 0.5022
Epoch 40/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.7691 - loss: 0.4843
Epoch 41/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.7552 - loss: 0.4903
Epoch 42/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - binary_accuracy: 0.7587 - loss: 0.4812
Epoch 43/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - binary_accuracy: 0.7569 - loss: 0.4998
Epoch 44/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.7674 - loss: 0.4747
Epoch 45/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.7587 - loss: 0.4919
Epoch 46/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.7413 - loss: 0.5080
Epoch 47/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.7760 - loss: 0.4802
Epoch 48/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.7569 - loss: 0.4878
Epoch 49/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - binary_accuracy: 0.7517 - loss: 0.4997
Epoch 50/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.7691 - loss: 0.5029
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
Epoch 1/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - binary_accuracy: 0.6510 - loss: 0.6834
Epoch 2/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - binary_accuracy: 0.6510 - loss: 0.6576
Epoch 3/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - binary_accuracy: 0.6510 - loss: 0.6232
Epoch 4/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.6510 - loss: 0.5900
Epoch 5/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.6510 - loss: 0.5807
Epoch 6/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.6510 - loss: 0.5637
Epoch 7/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - binary_accuracy: 0.6510 - loss: 0.5504
Epoch 8/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.6510 - loss: 0.5492
Epoch 9/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.6510 - loss: 0.5476
Epoch 10/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.6510 - loss: 0.5452
Epoch 11/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.6510 - loss: 0.5393
Epoch 12/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.6510 - loss: 0.5449
Epoch 13/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.6649 - loss: 0.5392
Epoch 14/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - binary_accuracy: 0.7760 - loss: 0.5264
Epoch 15/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.7622 - loss: 0.5277
Epoch 16/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.7483 - loss: 0.5204
Epoch 17/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.7639 - loss: 0.5184
Epoch 18/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.7726 - loss: 0.5233
Epoch 19/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.7656 - loss: 0.5263
Epoch 20/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - binary_accuracy: 0.7812 - loss: 0.5090
Epoch 21/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.7691 - loss: 0.5243
Epoch 22/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.7708 - loss: 0.5356
Epoch 23/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.7448 - loss: 0.5297
Epoch 24/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.7691 - loss: 0.5203
Epoch 25/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - binary_accuracy: 0.7726 - loss: 0.5318
Epoch 26/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - binary_accuracy: 0.7726 - loss: 0.5154
Epoch 27/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - binary_accuracy: 0.7396 - loss: 0.5180
Epoch 28/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - binary_accuracy: 0.7691 - loss: 0.5137
Epoch 29/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - binary_accuracy: 0.7448 - loss: 0.5180
Epoch 30/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - binary_accuracy: 0.7500 - loss: 0.5324
Epoch 31/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - binary_accuracy: 0.7622 - loss: 0.5177
Epoch 32/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - binary_accuracy: 0.7535 - loss: 0.5295
Epoch 33/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - binary_accuracy: 0.7656 - loss: 0.5100
Epoch 34/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - binary_accuracy: 0.7622 - loss: 0.5107
Epoch 35/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - binary_accuracy: 0.7483 - loss: 0.5281
Epoch 36/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - binary_accuracy: 0.7604 - loss: 0.5173
Epoch 37/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - binary_accuracy: 0.7552 - loss: 0.5187
Epoch 38/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.7552 - loss: 0.5191
Epoch 39/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.7587 - loss: 0.5165
Epoch 40/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - binary_accuracy: 0.7587 - loss: 0.5093
Epoch 41/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.7622 - loss: 0.5178
Epoch 42/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.7569 - loss: 0.4999
Epoch 43/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - binary_accuracy: 0.7517 - loss: 0.5258
Epoch 44/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.7587 - loss: 0.5089
Epoch 45/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.7483 - loss: 0.5230
Epoch 46/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.7587 - loss: 0.5199
Epoch 47/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.7500 - loss: 0.5173
Epoch 48/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.7431 - loss: 0.5026
Epoch 49/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - binary_accuracy: 0.7569 - loss: 0.5043
Epoch 50/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.7465 - loss: 0.5095
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
Epoch 1/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - binary_accuracy: 0.6389 - loss: 0.6875
Epoch 2/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.6510 - loss: 0.6773
Epoch 3/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.6510 - loss: 0.6697
Epoch 4/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.6510 - loss: 0.6640
Epoch 5/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - binary_accuracy: 0.6510 - loss: 0.6597
Epoch 6/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.6510 - loss: 0.6565
Epoch 7/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - binary_accuracy: 0.6510 - loss: 0.6540
Epoch 8/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.6510 - loss: 0.6521
Epoch 9/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.6510 - loss: 0.6506
Epoch 10/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.6510 - loss: 0.6495
Epoch 11/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - binary_accuracy: 0.6510 - loss: 0.6484
Epoch 12/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.6510 - loss: 0.6474
Epoch 13/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.6510 - loss: 0.6470
Epoch 14/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - binary_accuracy: 0.6510 - loss: 0.6462
Epoch 15/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.6510 - loss: 0.6454
Epoch 16/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.6510 - loss: 0.6448
Epoch 17/50

In [ ]:
best_params = gs.best_params_
# prga os melhores parametros
best_acc = gs.best_score_
#pega os melhores parametros

In [18]:
print(best_params)
print(best_acc)

{'batch_size': 10, 'epochs': 50, 'model__activation': 'relu', 'model__initializer': 'normal', 'model__loss': 'binary_crossentropy', 'model__neurons': 4, 'model__optimizer': 'adam'}
0.7669270833333334

In [ ]:
model =gs.best_estimator_
# melhor modelo

In [ ]:
predict = model.predict([[6,148,72,35,0	,33.6,0.627,50]])
#predição simples
predict

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step

array([1])

In [ ]:
model.model_.save('modelo_diabetes.keras')
#salva o modelo

In [ ]:
modelo_carregado = tf.keras.models.load_model('modelo_diabetes.keras')
# carrega o model salvo
dado_novo = [[65, 138, 32, 35, 0, 37.6, 0.627, 24]]
# lista para uma nova predição
dado_novo_scaled = scaler.transform(dado_novo)
# como eu usei o transformer, para inserir e necessario transforma-los
predict = modelo_carregado.predict(dado_novo_scaled)

/usr/local/lib/python3.12/dist-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 319ms/step

In [29]:
predict

array([[0.94792545]], dtype=float32)

In [30]:
if predict >0.8 :
  predict=True
else:
  predict=False

In [31]:
predict

True